name: update
on:
  pull_request:
    branches:
      - development
    types: [closed]
jobs:
  update-development:
    if: github.ref == 'refs/heads/development' && ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Check for MICROSOFT_TEAMS_WEBHOOK_URI
        run: |
          if [ -z "${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}" ]; then
            echo "You must provide an MICROSOFT_TEAMS_WEBHOOK_URI secret to relay EAS updates to MS Teams"
            exit 1
          fi

      - name: Send a message to Microsoft Teams
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
          title: Ignore This
          summary: EAS Build response
          text: It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
          theme_color: 00FF22
          sections: '[{ "activityTitle": "hello world" }]'
