name: update
on:
  pull_request:
    branches:
      - development
    types: [closed]
jobs:
  update-development:
    if: github.ref == 'refs/heads/development' && ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Check for MICROSOFT_TEAMS_WEBHOOK_URI
        run: |
          if [ -z "${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}" ]; then
            echo "You must provide an MICROSOFT_TEAMS_WEBHOOK_URI secret to relay EAS updates to MS Teams"
            exit 1
          fi

      - name: Send a message to Microsoft Teams
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
          title: Ignore This
          summary: <Message Summary>
          text: <Message Text>
          theme_color: green
          sections: '[{ "activityTitle": "hello world" }, { ... }]'
          actions: '[{ "@type": "OpenUri", "name": "lorem ipsum", "targets": [{ "os": "default", "uri": "https://localhost" }] }, { ... }]'
